Testing Login

diff --git a/.github/workflows/Test.yaml b/.github/workflows/Test.yaml
--- a/.github/workflows/Test.yaml
+++ b/.github/workflows/Test.yaml
@@ -81,7 +81,11 @@ jobs:
           service_url=$(minikube service trading-app-svc --url)
           echo "---------------opening the service----------------"
           curl $(minikube service trading-app-svc --url)/
-          ping -c 1 $(minikube service trading-app-svc --url)
+          if $?; then
+            echo "success"
+          else
+            echo "fail"
+          fi
           curl -X POST -d "name=TEST&email=test@gmail.com&password=test" $(minikube service trading-app-svc --url)/user/signup
           curl -X POST -d "email=test@gmail.com&password=test" $(minikube service trading-app-svc --url)/user/login
       #     curl $(minikube service tasksapp-svc --url)/tasks
